server:
  port: 8093
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: OrderService
  data:
    mongodb:
      host: localhost
      port: 27017
      database: orderDB

 zipkin:
   base-url: http://localhost:9411/
 sleuth:
   sampler:
     probability: 1 #100% (default = 10%)
