server:
  port: 8093
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: OrderService
  data:
    mongodb:
      host: localhost
      port: 27017
      database: orderDB
