
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: ShoppingCartService
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shoppingQueryDB
