server:
  port: 9200

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:876/eureka/

spring:
  application:
    name: ShoppingCartCommandServic
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shoppingCommandDB
