server:
  port: 9200

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: ShoppingCartCommandService
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shoppingCommandD
