server:
  port: 9201

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: ShoppingCartCommandService
  data:
    mongodb:
      host: localhost
      port: 27017
      database: shoppingCommandDB
  zipkin:
    base-url: http://localhost:9411/
  sleuth:
    sampler:
      probability: 1 #100% (default = 10%)
